class Autogenerated {
  List<AddressList>? addressList;
  List<ExpectedDelivery>? expectedDelivery;

  Autogenerated({this.addressList, this.expectedDelivery});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['addressList'] != null) {
      addressList = <AddressList>[];
      json['addressList'].forEach((v) {
        addressList!.add(new AddressList.fromJson(v));
      });
    }
    if (json['expectedDelivery'] != null) {
      expectedDelivery = <ExpectedDelivery>[];
      json['expectedDelivery'].forEach((v) {
        expectedDelivery!.add(new ExpectedDelivery.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.addressList != null) {
      data['addressList'] = this.addressList!.map((v) => v.toJson()).toList();
    }
    if (this.expectedDelivery != null) {
      data['expectedDelivery'] =
          this.expectedDelivery!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class AddressList {
  String? name;
  String? address;
  String? addressType;
  String? locality;
  String? state;
  String? city;
  String? pinCode;
  String? phone;

  AddressList(
      {this.name,
        this.address,
        this.addressType,
        this.locality,
        this.state,
        this.city,
        this.pinCode,
        this.phone});

  AddressList.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    address = json['address'];
    addressType = json['addressType'];
    locality = json['locality'];
    state = json['state'];
    city = json['city'];
    pinCode = json['pinCode'];
    phone = json['phone'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['address'] = this.address;
    data['addressType'] = this.addressType;
    data['locality'] = this.locality;
    data['state'] = this.state;
    data['city'] = this.city;
    data['pinCode'] = this.pinCode;
    data['phone'] = this.phone;
    return data;
  }
}

class ExpectedDelivery {
  String? image;
  String? name;
  String? date;

  ExpectedDelivery({this.image, this.name, this.date});

  ExpectedDelivery.fromJson(Map<String, dynamic> json) {
    image = json['image'];
    name = json['name'];
    date = json['date'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['image'] = this.image;
    data['name'] = this.name;
    data['date'] = this.date;
    return data;
  }
}